config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  root to: 'pages#home'
  get '/privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index]
    resources :conversations, only: [:show, :create] do
    resources :messages, only: [:create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :conversations, only: [:index, :show, :create] do
        resources :messages, only: [:show, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  has_many :sns_credentials, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :validatable, :confirmable

  def conversations
    Conversation.where(starter_id: id).or(Conversation.where(recipient_id: id))
  end

  def self.without_sns_data(auth)
    user = User.find_by(email: auth.info.email)
    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    user = User.find(snscredential.user_id)
    unless user.present?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
    end
    return { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user, sns: sns }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index

  def index
    @conversations = current_user.conversations.joins(:messages).order('messages.created_at DESC').uniq
    @users = User.where.not(id: @conversations.pluck(:starter_id, :recipient_id).flatten.uniq)
    @users = @users.where.not('id = ?', current_user.id)
    @list = @conversations + @users
    @list = Kaminari.paginate_array(@list).page(params[:page]).per(20)
    @new_conversation = Conversation.new
  end
end

app/views/users/index.html.erb
<div class="container">
  <h2>Members</h2>
  <% @list.each do |item| %>
    <% if item.class == Conversation %>
      <% if item.starter_id == current_user.id %>
        <% user = User.find(item.recipient_id) %>
      <% else %>
        <% user = User.find(item.starter_id)  %>
      <% end %>
      <%= link_to conversation_path(item) do %>
        <div class="card user-name">
          <div class="card-message">
            <% if item.messages.last.read == false && item.messages.last.sender != current_user %>
              <i class="fas fa-envelope-square"></i>
            <% end %>
              <div class="card-message-user">
                <%= user.name %>
              </div>
              <p><%= item.messages.last.content[0..20] %>...<p>
          </div>
          <div class="card-info">
            <small><%= item.messages.last.created_at.in_time_zone("Asia/Tokyo").strftime('%m/%d %H:%M') %></small>
            <div class="card-info-message">
              <p><%= item.messages.count %></p>
              <i class="fas fa-xs fa-comments"></i>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <% if current_user.conversations.find_by(starter_id: item.id) || current_user.conversations.find_by(recipient_id: item.id) %>
        <% current_user.conversations.find_by(starter_id: item.id) ? c = current_user.conversations.find_by(starter_id: item.id) : c =  current_user.conversations.find_by(recipient_id: item.id) %>
          <%= link_to conversation_path(c) do %>
            <div class="card user-name">
              <div class="card-message">
                <%= item.name %>
              </div>
            </div>
          <% end %>
      <% else %>
        <div class="card user-name">
          <div class="card-message">
            <%= item.name %>
            <%= simple_form_for(@new_conversation) do |f| %>
            <%= f.input :starter_id, as: :hidden, input_html: { value: current_user.id } %>
            <%= f.input :recipient_id, as: :hidden, input_html: { value: item.id } %>
            <%= button_tag type: "submit", class: "card-conversation-path"%>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= paginate @list, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b" %>
</div>